# Task

Rewrite the second call to pseudoAsync without declaring an anonymous function, does it throw an error? Use an ES5 Function method to get rid of the error
